### ISSUE TITLE
Be able to specify browser

### ISSUE THREAD

**Issue by KorySchneider** [KorySchneider/wikit#11]
`-b` flag still opens in default browser

`-b <browser>` to specify browser

**Comment by KorySchneider** [comment]
Due to the fact that we don't know if the user is going to specify a browser, the flags will have to be different.

**Comment by KorySchneider** [comment]
Using `-b` the same way, to open in default browser.

Current solution is to add a flag `--browser`, which expects a browser name directly afterwards, e.g. `wikit banana --browser firefox`.

**Comment by KorySchneider** [comment]
@ZaxonXP let me know your thoughts :^)

**Comment by ZaxonXP** [comment]
Sounds nice. The only problem I have is to get this version. If I do `npm install wikit -g` I am getting the version from the main branch. How can I get this version? Tried to clone the git code, but then I do not know how to install from it.

**Comment by KorySchneider** [comment]
Added in 1633a14cdc819652b6cae2b192c0ce70f3e29d46.

You can now run that same command, `npm i -g wikit`, to update and get the new feature.
