### ISSUE TITLE
Wikit always opens a browser without -b suffix

### ISSUE THREAD

**Issue by wiljaxon** [KorySchneider/wikit#13]
An example:

wikit Linux
Error: no output
Opening in browser...

**Comment by KorySchneider** [comment]
Confirmed something is fucky. Pushed a little fix a while ago but there are still some unaddressed issues. Thinking about a full rewrite in Python when I have some more free time.

**Comment by KorySchneider** [comment]
Fixed a number of other issues in release 2.4.0, which I just published. Update for more robust summary parsing and output! (`npm i -g wikit@latest`)
