### ISSUE TITLE
Problem with wikit in Kubuntu 18.04

### ISSUE THREAD

**Issue by veran2018** [KorySchneider/wikit#16]
Hello a couple of weeks ago I installed wikit.

The command that I used for the installation was:

sudo npm install wikit -g

The answer shown in the terminal was:

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/usr/local/bin/wikit -> /usr/local/lib/node_modules/wikit/index.js
\+ wikit@3.0.0
updated 1 package in 11.638s

I assumed that the program had been installed, but when making a query the result was the following:

argo@argo-desktop:~$ wikit Linux

/usr/local/bin/wikit: línea 2: use strict: orden no encontrada
/usr/local/bin/wikit: línea 4: error sintáctico cerca del elemento inesperado `('
/usr/local/bin/wikit: línea 4: `const path = require('path'),'

**Comment by KorySchneider** [comment]
Have you tried removing and reinstalling the package?

**Comment by veran2018** [comment]
Yes, many times.

**Comment by veran2018** [comment]
The program is installed. I don't think that's the problem. It appears that a couple of npm modules in the package.json.

**Comment by KorySchneider** [comment]
I've been unable to reproduce the errors. Please try this and let me know the results:

`sudo npm uninstall -g wikit && sudo rm /usr/local/bin/wikit -f && sudo rm /usr/local/lib/node_modules/wikit -rf && sudo npm i -g wikit`

Thanks!

**Comment by KorySchneider** [comment]
Also what node version are you running? `node --version`

**Comment by veran2018** [comment]
The node version is v8.10.0. I tried the commands you mentioned and the result is the same. Below the result seen on screen

- ansi@0.2.1 node_modules/wikit/node_modules/ansi
- ansi-escapes@3.1.0 node_modules/wikit/node_modules/ansi-escapes
- ansi-regex@3.0.0 node_modules/wikit/node_modules/ansi-regex
- aproba@1.2.0 node_modules/wikit/node_modules/aproba
- assert-plus@1.0.0 node_modules/wikit/node_modules/assert-plus
- asynckit@0.4.0 node_modules/wikit/node_modules/asynckit
- aws-sign2@0.7.0 node_modules/wikit/node_modules/aws-sign2
- aws4@1.8.0 node_modules/wikit/node_modules/aws4
- balanced-match@1.0.0 node_modules/wikit/node_modules/balanced-match
- boolbase@1.0.0 node_modules/wikit/node_modules/boolbase
- caseless@0.12.0 node_modules/wikit/node_modules/caseless
- chardet@0.7.0 node_modules/wikit/node_modules/chardet
- cli-spinners@1.3.1 node_modules/wikit/node_modules/cli-spinners
- cli-width@2.2.0 node_modules/wikit/node_modules/cli-width
- clone@1.0.4 node_modules/wikit/node_modules/clone
- co@4.6.0 node_modules/wikit/node_modules/co
- code-point-at@1.1.0 node_modules/wikit/node_modules/code-point-at
- color-name@1.1.3 node_modules/wikit/node_modules/color-name
- color-convert@1.9.3 node_modules/wikit/node_modules/color-convert
- ansi-styles@3.2.1 node_modules/wikit/node_modules/ansi-styles
- concat-map@0.0.1 node_modules/wikit/node_modules/concat-map
- brace-expansion@1.1.11 node_modules/wikit/node_modules/brace-expansion
- console-control-strings@1.1.0 node_modules/wikit/node_modules/console-control-strings
- core-util-is@1.0.2 node_modules/wikit/node_modules/core-util-is
- crypto-random-string@1.0.0 node_modules/wikit/node_modules/crypto-random-string
- css-what@2.1.0 node_modules/wikit/node_modules/css-what
- CSSwhat@0.4.7 node_modules/wikit/node_modules/CSSwhat
- dashdash@1.14.1 node_modules/wikit/node_modules/dashdash
- defaults@1.0.3 node_modules/wikit/node_modules/defaults
- delayed-stream@1.0.0 node_modules/wikit/node_modules/delayed-stream
- combined-stream@1.0.7 node_modules/wikit/node_modules/combined-stream
- delegates@1.0.0 node_modules/wikit/node_modules/delegates
- domelementtype@1.1.3 node_modules/wikit/node_modules/dom-serializer/node_modules/domelementtype
- domelementtype@1.3.0 node_modules/wikit/node_modules/domelementtype
- domutils@1.4.3 node_modules/wikit/node_modules/CSSselect/node_modules/domutils
- CSSselect@0.4.1 node_modules/wikit/node_modules/CSSselect
- domhandler@2.4.2 node_modules/wikit/node_modules/domhandler
- entities@1.1.1 node_modules/wikit/node_modules/entities
- dom-serializer@0.1.0 node_modules/wikit/node_modules/dom-serializer
- domutils@1.5.1 node_modules/wikit/node_modules/domutils
- escape-string-regexp@1.0.5 node_modules/wikit/node_modules/escape-string-regexp
- extend@3.0.2 node_modules/wikit/node_modules/extend
- extsprintf@1.3.0 node_modules/wikit/node_modules/extsprintf
- fast-deep-equal@1.1.0 node_modules/wikit/node_modules/fast-deep-equal
- fast-json-stable-stringify@2.0.0 node_modules/wikit/node_modules/fast-json-stable-stringify
- figures@2.0.0 node_modules/wikit/node_modules/figures
- forever-agent@0.6.1 node_modules/wikit/node_modules/forever-agent
- combined-stream@1.0.6 node_modules/wikit/node_modules/form-data/node_modules/combined-stream
- fs.realpath@1.0.0 node_modules/wikit/node_modules/fs.realpath
- ansi-regex@2.1.1 node_modules/wikit/node_modules/gauge/node_modules/ansi-regex
- strip-ansi@3.0.1 node_modules/wikit/node_modules/gauge/node_modules/strip-ansi
- getpass@0.1.7 node_modules/wikit/node_modules/getpass
- graceful-fs@4.1.11 node_modules/wikit/node_modules/graceful-fs
- har-schema@2.0.0 node_modules/wikit/node_modules/har-schema
- has-flag@3.0.0 node_modules/wikit/node_modules/has-flag
- has-unicode@2.0.1 node_modules/wikit/node_modules/has-unicode
- he@1.1.0 node_modules/wikit/node_modules/he
- imurmurhash@0.1.4 node_modules/wikit/node_modules/imurmurhash
- inherits@2.0.3 node_modules/wikit/node_modules/inherits
- is-fullwidth-code-point@2.0.0 node_modules/wikit/node_modules/is-fullwidth-code-point
- is-obj@1.0.1 node_modules/wikit/node_modules/is-obj
- dot-prop@4.2.0 node_modules/wikit/node_modules/dot-prop
- is-promise@2.1.0 node_modules/wikit/node_modules/is-promise
- is-typedarray@1.0.0 node_modules/wikit/node_modules/is-typedarray
- is-wsl@1.1.0 node_modules/wikit/node_modules/is-wsl
- isarray@1.0.0 node_modules/wikit/node_modules/isarray
- isstream@0.1.2 node_modules/wikit/node_modules/isstream
- jsbn@0.1.1 node_modules/wikit/node_modules/jsbn
- json-schema@0.2.3 node_modules/wikit/node_modules/json-schema
- json-schema-traverse@0.3.1 node_modules/wikit/node_modules/json-schema-traverse
- ajv@5.5.2 node_modules/wikit/node_modules/ajv
- har-validator@5.1.0 node_modules/wikit/node_modules/har-validator
- json-stringify-safe@5.0.1 node_modules/wikit/node_modules/json-stringify-safe
- limiter@1.1.3 node_modules/wikit/node_modules/limiter
- lodash@4.17.11 node_modules/wikit/node_modules/lodash
- lodash.assignin@4.2.0 node_modules/wikit/node_modules/lodash.assignin
- lodash.bind@4.2.1 node_modules/wikit/node_modules/lodash.bind
- lodash.defaults@4.2.0 node_modules/wikit/node_modules/lodash.defaults
- lodash.filter@4.6.0 node_modules/wikit/node_modules/lodash.filter
- lodash.flatten@4.4.0 node_modules/wikit/node_modules/lodash.flatten
- lodash.foreach@4.5.0 node_modules/wikit/node_modules/lodash.foreach
- lodash.map@4.6.0 node_modules/wikit/node_modules/lodash.map
- lodash.merge@4.6.1 node_modules/wikit/node_modules/lodash.merge
- lodash.pick@4.4.0 node_modules/wikit/node_modules/lodash.pick
- lodash.reduce@4.6.0 node_modules/wikit/node_modules/lodash.reduce
- lodash.reject@4.6.0 node_modules/wikit/node_modules/lodash.reject
- lodash.some@4.6.0 node_modules/wikit/node_modules/lodash.some
- mime-db@1.36.0 node_modules/wikit/node_modules/mime-db
- mime-types@2.1.20 node_modules/wikit/node_modules/mime-types
- form-data@2.3.2 node_modules/wikit/node_modules/form-data
- mimic-fn@1.2.0 node_modules/wikit/node_modules/mimic-fn
- minimatch@3.0.4 node_modules/wikit/node_modules/minimatch
- minimist@0.0.8 node_modules/wikit/node_modules/minimist
- mkdirp@0.5.1 node_modules/wikit/node_modules/mkdirp
- mute-stream@0.0.7 node_modules/wikit/node_modules/mute-stream
- domhandler@2.2.1 node_modules/wikit/node_modules/node-wikipedia/node_modules/domhandler
- entities@1.0.0 node_modules/wikit/node_modules/node-wikipedia/node_modules/htmlparser2/node_modules/entities
- isarray@0.0.1 node_modules/wikit/node_modules/node-wikipedia/node_modules/isarray
- lodash@2.4.2 node_modules/wikit/node_modules/node-wikipedia/node_modules/lodash
- string_decoder@0.10.31 node_modules/wikit/node_modules/node-wikipedia/node_modules/string_decoder
- readable-stream@1.1.14 node_modules/wikit/node_modules/node-wikipedia/node_modules/readable-stream
- htmlparser2@3.7.3 node_modules/wikit/node_modules/node-wikipedia/node_modules/htmlparser2
- cheerio@0.16.0 node_modules/wikit/node_modules/node-wikipedia/node_modules/cheerio
- npmlog@0.0.6 node_modules/wikit/node_modules/npmlog
- nth-check@1.0.1 node_modules/wikit/node_modules/nth-check
- css-select@1.2.0 node_modules/wikit/node_modules/css-select
- number-is-nan@1.0.1 node_modules/wikit/node_modules/number-is-nan
- is-fullwidth-code-point@1.0.0 node_modules/wikit/node_modules/gauge/node_modules/is-fullwidth-code-point
- string-width@1.0.2 node_modules/wikit/node_modules/gauge/node_modules/string-width
- oauth-sign@0.9.0 node_modules/wikit/node_modules/oauth-sign
- object-assign@4.1.1 node_modules/wikit/node_modules/object-assign
- onetime@2.0.1 node_modules/wikit/node_modules/onetime
- opn@5.4.0 node_modules/wikit/node_modules/opn
- os-tmpdir@1.0.2 node_modules/wikit/node_modules/os-tmpdir
- path-is-absolute@1.0.1 node_modules/wikit/node_modules/path-is-absolute
- performance-now@2.1.0 node_modules/wikit/node_modules/performance-now
- pify@3.0.0 node_modules/wikit/node_modules/pify
- make-dir@1.3.0 node_modules/wikit/node_modules/make-dir
- plumb@0.1.0 node_modules/wikit/node_modules/plumb
- process-nextick-args@2.0.0 node_modules/wikit/node_modules/process-nextick-args
- psl@1.1.29 node_modules/wikit/node_modules/psl
- punycode@1.4.1 node_modules/wikit/node_modules/punycode
- qs@6.5.2 node_modules/wikit/node_modules/qs
- run-async@2.3.0 node_modules/wikit/node_modules/run-async
- safe-buffer@5.1.2 node_modules/wikit/node_modules/safe-buffer
- safer-buffer@2.1.2 node_modules/wikit/node_modules/safer-buffer
- iconv-lite@0.4.24 node_modules/wikit/node_modules/iconv-lite
- ecc-jsbn@0.1.2 node_modules/wikit/node_modules/ecc-jsbn
- asn1@0.2.4 node_modules/wikit/node_modules/asn1
- set-blocking@2.0.0 node_modules/wikit/node_modules/set-blocking
- signal-exit@3.0.2 node_modules/wikit/node_modules/signal-exit
- restore-cursor@2.0.0 node_modules/wikit/node_modules/restore-cursor
- cli-cursor@2.1.0 node_modules/wikit/node_modules/cli-cursor
- string_decoder@1.1.1 node_modules/wikit/node_modules/string_decoder
- strip-ansi@4.0.0 node_modules/wikit/node_modules/strip-ansi
- string-width@2.1.1 node_modules/wikit/node_modules/string-width
- supports-color@5.5.0 node_modules/wikit/node_modules/supports-color
- chalk@2.4.1 node_modules/wikit/node_modules/chalk
- log-symbols@2.2.0 node_modules/wikit/node_modules/log-symbols
- through@2.3.8 node_modules/wikit/node_modules/through
- tmp@0.0.33 node_modules/wikit/node_modules/tmp
- external-editor@3.0.3 node_modules/wikit/node_modules/external-editor
- tough-cookie@2.4.3 node_modules/wikit/node_modules/tough-cookie
- tslib@1.9.3 node_modules/wikit/node_modules/tslib
- rxjs@6.3.3 node_modules/wikit/node_modules/rxjs
- inquirer@6.2.0 node_modules/wikit/node_modules/inquirer
- tunnel-agent@0.6.0 node_modules/wikit/node_modules/tunnel-agent
- tweetnacl@0.14.5 node_modules/wikit/node_modules/tweetnacl
- bcrypt-pbkdf@1.0.2 node_modules/wikit/node_modules/bcrypt-pbkdf
- sshpk@1.14.2 node_modules/wikit/node_modules/sshpk
- unique-string@1.0.0 node_modules/wikit/node_modules/unique-string
- util-deprecate@1.0.2 node_modules/wikit/node_modules/util-deprecate
- readable-stream@2.3.6 node_modules/wikit/node_modules/readable-stream
- htmlparser2@3.9.2 node_modules/wikit/node_modules/htmlparser2
- cheerio@0.22.0 node_modules/wikit/node_modules/cheerio
- html2plaintext@2.1.0 node_modules/wikit/node_modules/html2plaintext
- are-we-there-yet@1.1.5 node_modules/wikit/node_modules/are-we-there-yet
- uuid@3.3.2 node_modules/wikit/node_modules/uuid
- verror@1.10.0 node_modules/wikit/node_modules/verror
- jsprim@1.4.1 node_modules/wikit/node_modules/jsprim
- http-signature@1.2.0 node_modules/wikit/node_modules/http-signature
- request@2.88.0 node_modules/wikit/node_modules/request
- wcwidth@1.0.1 node_modules/wikit/node_modules/wcwidth
- ora@2.1.0 node_modules/wikit/node_modules/ora
- wide-align@1.1.3 node_modules/wikit/node_modules/wide-align
- gauge@2.7.4 node_modules/wikit/node_modules/gauge
- npmlog@4.1.2 node_modules/wikit/node_modules/downcache/node_modules/npmlog
- wrappy@1.0.2 node_modules/wikit/node_modules/wrappy
- once@1.4.0 node_modules/wikit/node_modules/once
- inflight@1.0.6 node_modules/wikit/node_modules/inflight
- glob@7.1.3 node_modules/wikit/node_modules/glob
- rimraf@2.6.2 node_modules/wikit/node_modules/rimraf
- downcache@0.1.0 node_modules/wikit/node_modules/downcache
- node-wikipedia@0.0.2 node_modules/wikit/node_modules/node-wikipedia
- write-file-atomic@2.3.0 node_modules/wikit/node_modules/write-file-atomic
- xdg-basedir@3.0.0 node_modules/wikit/node_modules/xdg-basedir
- configstore@3.1.2 node_modules/wikit/node_modules/configstore
- wikit@3.0.0 node_modules/wikit

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/usr/local/bin/wikit -> /usr/local/lib/node_modules/wikit/index.js
/usr/local/lib
└─┬ wikit@3.0.0 
  ├─┬ configstore@3.1.2 
  │ ├─┬ dot-prop@4.2.0 
  │ │ └── is-obj@1.0.1 
  │ ├── graceful-fs@4.1.11 
  │ ├─┬ make-dir@1.3.0 
  │ │ └── pify@3.0.0 
  │ ├─┬ unique-string@1.0.0 
  │ │ └── crypto-random-string@1.0.0 
  │ ├─┬ write-file-atomic@2.3.0 
  │ │ ├── imurmurhash@0.1.4 
  │ │ └── signal-exit@3.0.2 
  │ └── xdg-basedir@3.0.0 
  ├─┬ html2plaintext@2.1.0 
  │ ├─┬ cheerio@0.22.0 
  │ │ ├─┬ css-select@1.2.0 
  │ │ │ ├── boolbase@1.0.0 
  │ │ │ ├── css-what@2.1.0 
  │ │ │ ├── domutils@1.5.1 
  │ │ │ └── nth-check@1.0.1 
  │ │ ├─┬ dom-serializer@0.1.0 
  │ │ │ └── domelementtype@1.1.3 
  │ │ ├── entities@1.1.1 
  │ │ ├─┬ htmlparser2@3.9.2 
  │ │ │ ├── domelementtype@1.3.0 
  │ │ │ ├── domhandler@2.4.2 
  │ │ │ ├── inherits@2.0.3 
  │ │ │ └─┬ readable-stream@2.3.6 
  │ │ │   ├── core-util-is@1.0.2 
  │ │ │   ├── isarray@1.0.0 
  │ │ │   ├── process-nextick-args@2.0.0 
  │ │ │   ├── string_decoder@1.1.1 
  │ │ │   └── util-deprecate@1.0.2 
  │ │ ├── lodash.assignin@4.2.0 
  │ │ ├── lodash.bind@4.2.1 
  │ │ ├── lodash.defaults@4.2.0 
  │ │ ├── lodash.filter@4.6.0 
  │ │ ├── lodash.flatten@4.4.0 
  │ │ ├── lodash.foreach@4.5.0 
  │ │ ├── lodash.map@4.6.0 
  │ │ ├── lodash.merge@4.6.1 
  │ │ ├── lodash.pick@4.4.0 
  │ │ ├── lodash.reduce@4.6.0 
  │ │ ├── lodash.reject@4.6.0 
  │ │ └── lodash.some@4.6.0 
  │ ├── he@1.1.0 
  │ └── plumb@0.1.0 
  ├─┬ inquirer@6.2.0 
  │ ├── ansi-escapes@3.1.0 
  │ ├─┬ chalk@2.4.1 
  │ │ ├─┬ ansi-styles@3.2.1 
  │ │ │ └─┬ color-convert@1.9.3 
  │ │ │   └── color-name@1.1.3 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ └─┬ supports-color@5.5.0 
  │ │   └── has-flag@3.0.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   └─┬ onetime@2.0.1 
  │ │     └── mimic-fn@1.2.0 
  │ ├── cli-width@2.2.0 
  │ ├─┬ external-editor@3.0.3 
  │ │ ├── chardet@0.7.0 
  │ │ ├─┬ iconv-lite@0.4.24 
  │ │ │ └── safer-buffer@2.1.2 
  │ │ └─┬ tmp@0.0.33 
  │ │   └── os-tmpdir@1.0.2 
  │ ├── figures@2.0.0 
  │ ├── lodash@4.17.11 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├─┬ rxjs@6.3.3 
  │ │ └── tslib@1.9.3 
  │ ├─┬ string-width@2.1.1 
  │ │ └── is-fullwidth-code-point@2.0.0 
  │ ├─┬ strip-ansi@4.0.0 
  │ │ └── ansi-regex@3.0.0 
  │ └── through@2.3.8 
  ├─┬ node-wikipedia@0.0.2 
  │ ├─┬ cheerio@0.16.0 
  │ │ ├─┬ CSSselect@0.4.1 
  │ │ │ ├── CSSwhat@0.4.7 
  │ │ │ └── domutils@1.4.3 
  │ │ ├─┬ htmlparser2@3.7.3 
  │ │ │ ├── domhandler@2.2.1 
  │ │ │ ├── entities@1.0.0 
  │ │ │ └─┬ readable-stream@1.1.14 
  │ │ │   ├── isarray@0.0.1 
  │ │ │   └── string_decoder@0.10.31 
  │ │ └── lodash@2.4.2 
  │ ├─┬ downcache@0.1.0 
  │ │ ├── extend@3.0.2 
  │ │ ├── limiter@1.1.3 
  │ │ ├─┬ mkdirp@0.5.1 
  │ │ │ └── minimist@0.0.8 
  │ │ ├─┬ npmlog@4.1.2 
  │ │ │ ├─┬ are-we-there-yet@1.1.5 
  │ │ │ │ └── delegates@1.0.0 
  │ │ │ ├── console-control-strings@1.1.0 
  │ │ │ ├─┬ gauge@2.7.4 
  │ │ │ │ ├── aproba@1.2.0 
  │ │ │ │ ├── has-unicode@2.0.1 
  │ │ │ │ ├── object-assign@4.1.1 
  │ │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ │ ├── code-point-at@1.1.0 
  │ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │ │   └── number-is-nan@1.0.1 
  │ │ │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ │ │ └── ansi-regex@2.1.1 
  │ │ │ │ └── wide-align@1.1.3 
  │ │ │ └── set-blocking@2.0.0 
  │ │ └─┬ rimraf@2.6.2 
  │ │   └─┬ glob@7.1.3 
  │ │     ├── fs.realpath@1.0.0 
  │ │     ├─┬ inflight@1.0.6 
  │ │     │ └── wrappy@1.0.2 
  │ │     ├─┬ minimatch@3.0.4 
  │ │     │ └─┬ brace-expansion@1.1.11 
  │ │     │   ├── balanced-match@1.0.0 
  │ │     │   └── concat-map@0.0.1 
  │ │     ├── once@1.4.0 
  │ │     └── path-is-absolute@1.0.1 
  │ ├─┬ npmlog@0.0.6 
  │ │ └── ansi@0.2.1 
  │ └─┬ request@2.88.0 
  │   ├── aws-sign2@0.7.0 
  │   ├── aws4@1.8.0 
  │   ├── caseless@0.12.0 
  │   ├─┬ combined-stream@1.0.7 
  │   │ └── delayed-stream@1.0.0 
  │   ├── forever-agent@0.6.1 
  │   ├─┬ form-data@2.3.2 
  │   │ ├── asynckit@0.4.0 
  │   │ └── combined-stream@1.0.6 
  │   ├─┬ har-validator@5.1.0 
  │   │ ├─┬ ajv@5.5.2 
  │   │ │ ├── co@4.6.0 
  │   │ │ ├── fast-deep-equal@1.1.0 
  │   │ │ ├── fast-json-stable-stringify@2.0.0 
  │   │ │ └── json-schema-traverse@0.3.1 
  │   │ └── har-schema@2.0.0 
  │   ├─┬ http-signature@1.2.0 
  │   │ ├── assert-plus@1.0.0 
  │   │ ├─┬ jsprim@1.4.1 
  │   │ │ ├── extsprintf@1.3.0 
  │   │ │ ├── json-schema@0.2.3 
  │   │ │ └── verror@1.10.0 
  │   │ └─┬ sshpk@1.14.2 
  │   │   ├── asn1@0.2.4 
  │   │   ├── bcrypt-pbkdf@1.0.2 
  │   │   ├── dashdash@1.14.1 
  │   │   ├── ecc-jsbn@0.1.2 
  │   │   ├── getpass@0.1.7 
  │   │   ├── jsbn@0.1.1 
  │   │   └── tweetnacl@0.14.5 
  │   ├── is-typedarray@1.0.0 
  │   ├── isstream@0.1.2 
  │   ├── json-stringify-safe@5.0.1 
  │   ├─┬ mime-types@2.1.20 
  │   │ └── mime-db@1.36.0 
  │   ├── oauth-sign@0.9.0 
  │   ├── performance-now@2.1.0 
  │   ├── qs@6.5.2 
  │   ├── safe-buffer@5.1.2 
  │   ├─┬ tough-cookie@2.4.3 
  │   │ ├── psl@1.1.29 
  │   │ └── punycode@1.4.1 
  │   ├── tunnel-agent@0.6.0 
  │   └── uuid@3.3.2 
  ├─┬ opn@5.4.0 
  │ └── is-wsl@1.1.0 
  └─┬ ora@2.1.0 
    ├── cli-spinners@1.3.1 
    ├── log-symbols@2.2.0 
    └─┬ wcwidth@1.0.1 
      └─┬ defaults@1.0.3 
        └── clone@1.0.4

**Comment by KorySchneider** [comment]
Thanks for the note @rgamec !

@veran2018 are you able to upgrade to node 11?
