### ISSUE TITLE
Language flag not honored in combination with other flags

### ISSUE THREAD

**Issue by fethomm** [KorySchneider/wikit#19]
Wikit does not honor the lang flag when flags like -b, -d or -D are used at the same time. This always opens the English version of the article. Even changing lang default in wikit.json does not change this behaviour. The language I tried this with is German (de). Am I missing something or does this just not work?

**Comment by rgamec** [comment]
Hi @fethomm 

I've created a pull request #20 to deal with this issue, let me know if it helps. I've successfully tested it with DE/IT/FR/ES languages and the -b option switch.

Thanks

**Comment by fethomm** [comment]
> R Game <notifications@github.com> hat am 7. April 2019 um 11:36 geschrieben:
> 
> 
> Hi @fethomm 
> 
> I've created a pull request #20 to deal with this issue, let me know if it helps. I've successfully tested it with DE/IT/FR/ES languages and the -b option switch.

Wow, thanks for your quick response. Will test sometime today and let you know.

**Comment by fethomm** [comment]
Works for me too. Thanks for fixing this.

**Comment by KorySchneider** [comment]
Thanks for opening this issue @fethomm, and thanks for the quick PR @rgamec!

I've fixed the browser disambiguation page opening in other languages in c1322289c7934bd28b1849a49ea64b92680b261d, and am going to spend some more time thinking about how to get the CLI disambiguation menu working. I'm don't really want to push the hack in #20, but I would rather implement something like yargs or minimist.

**Comment by KorySchneider** [comment]
Added minimist in 5d8355199c2b80d77dbbfeb4f614dccec2fd72d9, which should achieve the same results as the quick fix from @rgamec and also reduced file length by about 50 lines.

**Comment by KorySchneider** [comment]
@fethomm @rgamec I have published the latest changes to npm, `npm i -g wikit` to update.

**Comment by fethomm** [comment]
> Kory Schneider <notifications@github.com> hat am 7. April 2019 um 22:06 geschrieben:
> 
> 
> @fethomm @rgamec I have published the latest changes to npm, `npm i -g wikit` to update.
>
Thank you. I tested Wikit for an article for a German linux print magazine, that I finished writing today. Good to know my German readers will install a version that works with DE language.

**Comment by KorySchneider** [comment]
@fethomm What is the magazine? Would love to see the article if you have a link to an online version!

**Comment by fethomm** [comment]
> Kory Schneider <notifications@github.com> hat am 8. April 2019 um 01:55 geschrieben:
> 
> 
> @fethomm What is the magazine? Would love to see the article if you have a link to an online version!

The magazine is LinuxUser [1]. I sent the article to my editor yesterday and it will be publisdhed in issue 06/2019, which will be on the shelves on May 23. At that point you can read the first page online for free, only after a year will it be freely available. Until then it would be 99 cent to buy.

The article might be translated and published in international Linux Magazine [2] a couple months later.
> -- 


[1]: https://www.linux-user.de/
[2]: http://www.linux-magazine.com/

**Comment by KorySchneider** [comment]
> The magazine is LinuxUser

Very cool, thank you!
