### ISSUE TITLE
Wikit  process doesn't exit in bash script or in terminal.

### ISSUE THREAD

**Issue by Amooti73** [KorySchneider/wikit#33]
I have tried these commands in gnome terminal to pipe the disambiguation results into a file:

`wikit rotation -d --line 80 > list.txt`

and

`wikit rotation -d --line 80 | cat > list.txt`

I want to use this in the following script converted to a text file for safe uploading:

[diswik.txt](https://github.com/KorySchneider/wikit/files/4487328/diswik.txt)

Might you have any idea why the command (on line 13 in the script) keeps running.  If I press Ctrl-c the two cli commands and the script terminate successfully!

Thanks!

P.S. I believe I installed wikit with npm, and can't remember for sure whether or not I cloned it from this repository! Sorry!

**Comment by Amooti73** [comment]
It seems this problem arose because the attempt to send the disambiguation list to a file results in sending only the results that are visible in the terminal and not those which only become visible upon scrolling.  With the help of [moosotc](https://github.com/moosotc) who suggested appending

`</dev/null`

to make the command, or line in the script, to read:

`wikit rotation -d --line 80 > list.txt </dev/null`

I had also posted this issue as a question [here](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de/580723#580723), but now I have answered it.

The unfinished business is whether or not there is a way to send all the disambiguation results to a file with wikit.

**Comment by KorySchneider** [comment]
My guess is the wikit process continued to run because it was waiting for input from the user (scrolling through and selecting an item from the disambiguation list).


> The unfinished business is whether or not there is a way to send all the disambiguation results to a file with wikit.

I could potentially add `--disambiguation-all-summaries` and `--disambiguation-all-full` flags to output all summaries/full articles for all the disambiguous articles, would this be helpful?

**Comment by Amooti73** [comment]
Thanks for your response!
Yes, I would find it helpful, at least for the script I was working on.  Hopefully, some others might also find it helpful.

I would be grateful!
