### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory, Error when trying to execute wikit command in ubuntu

### ISSUE THREAD

**Issue by delcin-raj** [KorySchneider/wikit#35]
I have installed wikit using,
 sudo npm install wikit -g
command in ubuntu after installing npm. The installation was complete and the program is found in 
/usr/local/bin/wikit
But I'm getting the error as mentioned in the title

**Comment by KorySchneider** [comment]
Which operating system are you running? Might also check the output of `$ which node`.

Side note, it is recommended to not install npm packages with sudo. If you are needing to use sudo to install packages globally this indicates permissions issues with npm and/or the directory where global packages live.

**Comment by delcin-raj** [comment]
I'm using ubuntu. It is not possible to install without sudo.
The result of $ which node, is /usr/bin/node.
Based on my search in github regarding similar problems with other programs
it seems that some packages has
windows format. In windows '\' used instead of '/' to delimit the path.
That is why ubuntu is not recognising 'node\r' it seems.

Thanks,
Delcin

**Comment by KorySchneider** [comment]
> it seems that some packages has windows format

This seems possible as I was on Windows when I pushed the last release, but I cannot find any `\r` characters in the source code. Also, I have no issues running the latest version (4.4.0) on Ubuntu or Windows. Which version of wikit do you have installed?

> The result of $ which node, is /usr/bin/node

That should work.

> It is not possible to install without sudo

...depending on your npm configuration and filesystem permissions (see [here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)). I don't think this is related to the issue though.

**Comment by KorySchneider** [comment]
Closing - no repro
