### ISSUE TITLE
Please add multilanguage support

### ISSUE THREAD

**Issue by zlaxy** [KorySchneider/wikit#4]
I want to read articles in two languages. Please, add maybe config file, where it possible to add priority of search, for example:
ru
en
(for first searching in http://ru.wikipedia.org/, and second: https://en.wikipedia.org/)
After using: `wikit cia` - i want to see two articles in terminal: firts https://ru.wikipedia.org/wiki/CIA and second https://en.wikipedia.org/wiki/CIA

Thanks!

**Comment by KorySchneider** [comment]
Good idea! I will look into implementing this.

**Comment by zlaxy** [comment]
I made basic implementation, please, check this out: https://github.com/KorySchneider/wikit/pull/5/commits/82941c223f83c1f0fa160b842dfedd47c6e764fe

**Comment by KorySchneider** [comment]
Added in 272625358168236cc0710ba2ede3c43d682cb511
