### ISSUE TITLE
Executable not working on Mac

### ISSUE THREAD

**Issue by andywenk** [KorySchneider/wikit#40]
Thanks for that nice little script. 

The newlines are not correctly formatted for Mac. The error is

`env: node\r: No such file or directory`

This can be fixed with solutions posted here: https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by KorySchneider** [comment]
Hi, you are the second person to report this bug but I haven't been able to reproduce it.

I tried both the dos2unix program and the vim solutions in that link (as well as other solutions previously) to no avail. Please make sure you are running the latest version (`npm i -g wikit@latest`) and let me know if the problem persists.
