### ISSUE TITLE
wikit AI

### ISSUE THREAD

**Issue by dikdollan** [KorySchneider/wikit#43]
this was built in Zsh for Mac but should run fine if you convert (say) to (espeak) the linux -eq of macs "say" command.
also you would have to do something with var1 it's just a voice selection for mac. I use this more than Siri since I Am always working in my terminal. I am about to add him to my headless ubuntu V.M.  I was working on my own way to filter the text from a wiki pull when I found this saved me a bunch of time. Thanks   

#!/bin/bash
v1="Daniel"
v3="y"
v4="/Users/~/DarwinAi/result"
v5="sleep .5s"
v6=('y' 'Y' 'yes' 'Yes' 'YEs' 'YES' 'yES' 'yeS')
v7=('n' 'N' 'no' 'No' 'NO' 'No')

repeat (){
    read -p "What Is/ Are: " v2
say -v $v1 "I Am searching for info on "$v2"" 
wikit $v2 > $v4"$v2".txt
say -v $v1 -f $v4"$v2".txt;$v5
rm $v4"$v2".txt
}

say -v $v1 "Hello My Name Is Darwin";$v5
say -v $v1 "I Answer Questions In The Form of What Is"

repeat 

until [[ $v3 == $v7 ]] 
     do    
      say -v $v1 "Do you have another Question"
       read -p "y/n: " v3
                 
        if [[ $v3 == "$v6" ]]
           then

              repeat 

           elif [[ $v3 == $v7 ]]
              then
                  break
           else
              say -v $v1 "sorry I do not understand"
        fi 

done

say -v $v1 "Goodbye"

**Comment by KorySchneider** [comment]
Hi, cool to see wikit helped you out, thanks for sharing!
