### ISSUE TITLE
Query string should be a match even without uppercase letters to retrive results

### ISSUE THREAD

**Issue by gabriel-ballesteros** [KorySchneider/wikit#46]
For example, actually `wikit Mato Grosso do Sul` retrieves that exact wikipedia page but `wikit mato grosso do sul` does not. Is it ok that uppercase letters matter to match results?

**Comment by KorySchneider** [comment]
Interesting, thanks for reporting. I can't say when I'll have time to look into this, but PRs are welcome!

**Comment by pendragons-code** [comment]
I can confirm that this is the case, however, I noticed some inconsistencies with regards to the usage and success of queries with such uppercase letters.

![image](https://user-images.githubusercontent.com/88629349/187487421-f1896f77-afd1-4682-9c05-3da24af22a1c.png)

![image](https://user-images.githubusercontent.com/88629349/187487600-0788667f-f8b3-4715-909b-8001fd5294bf.png)

**Comment by pendragons-code** [comment]
https://en.wikipedia.org/wiki/Mato_grosso_do_sul


![image](https://user-images.githubusercontent.com/88629349/187489913-c141c6cf-5c79-4af9-8c0a-98b805f7db8b.png)


Other reasons this message is displayed

`Titles on Wikipedia are [case sensitive](https://en.wikipedia.org/wiki/Case_sensitivity) except for the first character; please [check alternative capitalizations](https://en.wikipedia.org/w/index.php?search=Mato+grosso+do+sul&title=Special%3ASearch&fulltext=1) and consider adding a [redirect](https://en.wikipedia.org/wiki/Wikipedia:Redirect) here to the correct title.`


looks like we just need to add a redirect lol.
