### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by whit2333** [KorySchneider/wikit#6]
Very nice work! I have some suggestions and feature requests:

1. Perhaps add a `-d` option for the disambiguation page. Maybe a numbered list to be selected? https://en.wikipedia.org/wiki/Root_(disambiguation)
2. Similarly adding a `-s` option for listing the sections so they can be selected. This would be really cool.
3. Parse (or don't change) any math/equations. It is probably best to leave it as markup. For example `wikit polynomial` has an equation in the first paragraph. This would also help printing sections, e.g., to get a quick reference to an equation.

Cheers

**Comment by KorySchneider** [comment]
Thank you! These are good suggestions.

Re: 1 and 2, I am about to add a disambiguation flag (`-d`) which will open the disambiguation page in the browser. This is a lot quicker and easier than writing an interface to browse through the options (Though that would be pretty sweet; feel free to work on it and open a PR).

I'm not quite sure what 3 is asking, what do you mean by "leave it as markup"? I do like the idea of quick equation reference.

**Comment by KorySchneider** [comment]
Added disambiguation flag in 5d674046aa1959de0e7f00eed14cab4b997198e8

**Comment by KorySchneider** [comment]
Hey @whit2333 I finally got around to this! `npm i -g wikit@latest` to upgrade :\^)

`-d` opens the new CLI menu, `-D` opens the disambiguation page in the browser.
