### ISSUE TITLE
Some queris return empty result

### ISSUE THREAD

**Issue by copyme** [KorySchneider/wikit#7]
I have tried wikit with some entries like "Gaussian integer" and it did not return anything.

**Comment by KorySchneider** [comment]
Looking into this

**Comment by KorySchneider** [comment]
Don't have a lot of time this morning so a I added a quick fix in 62253ccd4364385546455a0eb31aa6143d7eb3aa.

If there is no output, the article will open in the browser instead.

**Comment by KorySchneider** [comment]
Closing for now, though I may implement a better solution in the future.
