### ISSUE TITLE
Opening in browser does not open in browser over SSH

### ISSUE THREAD

**Issue by ZaxonXP** [KorySchneider/wikit#9]
If I try to open in browser using option -b how the wikit know in which browser to open?

I am trying to search for some term working remotely over SSH. No browser will open. How can I force the wikit to open the link in w3m browser?

**Comment by KorySchneider** [comment]
To clarify, you're in a terminal on your local computer, SSH'd into a remote computer, but trying to open an article in the browser on your local computer?

**Comment by ZaxonXP** [comment]
Using a tablet and termux I ssh to remote machine and atach the tmux session. Then I use wikit with -b option and expect to have the article opened in the terminal browser (w3m). However nothing opening. Is there some shell variable to set up, so wikit will know which browser to use?

**Comment by KorySchneider** [comment]
Is w3m set to be your default browser?

Wikit uses [opn](https://www.npmjs.com/package/opn) to open links in the default browser. It does look like opn supports choosing which browser to open in -- feel free to fork wikit and play around with this!

**Comment by ZaxonXP** [comment]
@KorySchneider: Would it be possible  that you could add an option to open in the specified browser (like w3m, links, lynx)? Or tell me how to set the default browser to w3m?

Thanks with a suggestion to fork it, but I am not so strong in this language.

**Comment by KorySchneider** [comment]
I could look into implementing this, yes. I'm on break right now so I have some free time, and it seems like a reasonable feature :^)

**Comment by KorySchneider** [comment]
Opened new issue for this #11
